const restaurantList = [
    {
        info: {
        id: "123456",
        name: "Pizza Paradise",
        cloudinaryImageId: "https://images.unsplash.com/photo-1601924582975-6d1d6a8f8f4f?w=1200&q=80&auto=format&fit=crop",
        locality: "MG Road",
        areaName: "Central District",
        costForTwo: "₹400 for two",
        cuisines: ["Pizza", "Italian", "Fast Food"],
        avgRating: 4.3,
        avgRatingString: "4.3",
        totalRatingsString: "10K+ ratings",
        veg: false,
        sla: {
            deliveryTime: 30,
            lastMileTravel: 3.5,
            slaString: "30 mins",
        },
        aggregatedDiscountInfoV3: {
            header: "50% OFF",
            subHeader: "UPTO ₹100",
        },
        },
    },
    {
        info: {
        id: "789012",
        name: "Sushi World",
        cloudinaryImageId: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&q=80&auto=format&fit=crop",
        locality: "Koramangala",
        areaName: "Central District",
        costForTwo: "₹500 for two",
        cuisines: ["Japanese", "Sushi", "Asian"],
        avgRating: 4.5,
        avgRatingString: "4.5",
        totalRatingsString: "8K+ ratings",
        veg: false,
        sla: {
            deliveryTime: 25,
            lastMileTravel: 2.5,
            slaString: "25 mins",
        },
        aggregatedDiscountInfoV3: {
            header: "40% OFF",
            subHeader: "UPTO ₹80",
        },
        },
    },
    {
        info: {
        id: "345678",
        name: "Green Garden",
        cloudinaryImageId: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1200&q=80&auto=format&fit=crop",
        locality: "Indiranagar",
        areaName: "Central District",
        costForTwo: "₹300 for two",
        cuisines: ["Vegetarian", "Salads", "Healthy"],
        avgRating: 4.0,
        avgRatingString: "4.0",
        totalRatingsString: "5K+ ratings",
        veg: true,
        sla: {
            deliveryTime: 20,
            lastMileTravel: 1.5,
            slaString: "20 mins",
        },
        aggregatedDiscountInfoV3: {
            header: "30% OFF",
            subHeader: "UPTO ₹50",
        },
        }
    },
    {
        info: {
        id: "901234",
        name: "Taco Town",
        cloudinaryImageId: "https://images.unsplash.com/photo-1544025162-1b8a9b9e1f3d?w=1200&q=80&auto=format&fit=crop",
        locality: "Brigade Road",
        areaName: "Central District",
        costForTwo: "₹250 for two",
        cuisines: ["Mexican", "Tacos"],
        avgRating: 4.1,
        avgRatingString: "4.1",
        totalRatingsString: "3K+ ratings",
        veg: false,
        sla: { deliveryTime: 22, lastMileTravel: 2.0, slaString: "22 mins" },
        aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
        }
    },
    {
        info: {
        id: "112233",
        name: "Burger Barn",
        cloudinaryImageId: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&q=80&auto=format&fit=crop",
        locality: "HSR Layout",
        areaName: "South Zone",
        costForTwo: "₹350 for two",
        cuisines: ["Burgers", "Fast Food"],
        avgRating: 4.2,
        avgRatingString: "4.2",
        totalRatingsString: "6K+ ratings",
        veg: false,
        sla: { deliveryTime: 28, lastMileTravel: 3.0, slaString: "28 mins" },
        aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹90" },
        }
    },
    {
        info: {
        id: "223344",
        name: "Curry Corner",
        cloudinaryImageId: "https://images.unsplash.com/photo-1604908177220-6f3b3f9f1a7a?w=1200&q=80&auto=format&fit=crop",
        locality: "Jayanagar",
        areaName: "South Zone",
        costForTwo: "₹320 for two",
        cuisines: ["Indian", "Curry"],
        avgRating: 4.4,
        avgRatingString: "4.4",
        totalRatingsString: "7K+ ratings",
        veg: false,
        sla: { deliveryTime: 24, lastMileTravel: 2.8, slaString: "24 mins" },
        aggregatedDiscountInfoV3: { header: "35% OFF", subHeader: "UPTO ₹70" },
        }
    },
    {
        info: {
        id: "334455",
        name: "Pasta House",
        cloudinaryImageId: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=1200&q=80&auto=format&fit=crop",
        locality: "Malleshwaram",
        areaName: "North Zone",
        costForTwo: "₹420 for two",
        cuisines: ["Italian", "Pasta"],
        avgRating: 4.0,
        avgRatingString: "4.0",
        totalRatingsString: "4K+ ratings",
        veg: false,
        sla: { deliveryTime: 27, lastMileTravel: 3.2, slaString: "27 mins" },
        aggregatedDiscountInfoV3: { header: "20% OFF", subHeader: "UPTO ₹50" },
        }
    },
    {
        info: {
        id: "445566",
        name: "Noodle Nook",
        cloudinaryImageId: "https://images.unsplash.com/photo-1543353071-087092ec393a?w=1200&q=80&auto=format&fit=crop",
        locality: "Koramangala",
        areaName: "Central District",
        costForTwo: "₹280 for two",
        cuisines: ["Chinese", "Noodles"],
        avgRating: 3.9,
        avgRatingString: "3.9",
        totalRatingsString: "2K+ ratings",
        veg: false,
        sla: { deliveryTime: 21, lastMileTravel: 1.9, slaString: "21 mins" },
        aggregatedDiscountInfoV3: { header: "15% OFF", subHeader: "UPTO ₹40" },
        }
    },
    {
        info: {
        id: "556677",
        name: "BBQ Bliss",
        cloudinaryImageId: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80&auto=format&fit=crop",
        locality: "Electronic City",
        areaName: "South Zone",
        costForTwo: "₹600 for two",
        cuisines: ["BBQ", "Grill"],
        avgRating: 4.6,
        avgRatingString: "4.6",
        totalRatingsString: "9K+ ratings",
        veg: false,
        sla: { deliveryTime: 35, lastMileTravel: 4.5, slaString: "35 mins" },
        aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹150" },
        }
    },
    {
        info: {
        id: "667788",
        name: "Dessert Den",
        cloudinaryImageId: "https://images.unsplash.com/photo-1543933040-1b9d7d7d4d7a?w=1200&q=80&auto=format&fit=crop",
        locality: "Whitefield",
        areaName: "East Zone",
        costForTwo: "₹200 for two",
        cuisines: ["Desserts", "Bakery"],
        avgRating: 4.3,
        avgRatingString: "4.3",
        totalRatingsString: "5K+ ratings",
        veg: true,
        sla: { deliveryTime: 18, lastMileTravel: 1.2, slaString: "18 mins" },
        aggregatedDiscountInfoV3: { header: "20% OFF", subHeader: "UPTO ₹30" },
        }
    },
    {
        info: {
        id: "778899",
        name: "Salad Stop",
        cloudinaryImageId: "https://images.unsplash.com/photo-1523986371872-9d3ba2e2f642?w=1200&q=80&auto=format&fit=crop",
        locality: "Richmond Town",
        areaName: "Central District",
        costForTwo: "₹260 for two",
        cuisines: ["Salads", "Healthy"],
        avgRating: 4.1,
        avgRatingString: "4.1",
        totalRatingsString: "1.5K+ ratings",
        veg: true,
        sla: { deliveryTime: 16, lastMileTravel: 1.0, slaString: "16 mins" },
        aggregatedDiscountInfoV3: { header: "10% OFF", subHeader: "UPTO ₹20" },
        }
    },
    {
        info: {
        id: "889900",
        name: "Bagel Bros",
        cloudinaryImageId: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&q=80&auto=format&fit=crop",
        locality: "MG Road",
        areaName: "Central District",
        costForTwo: "₹220 for two",
        cuisines: ["Bakery", "Breakfast"],
        avgRating: 4.0,
        avgRatingString: "4.0",
        totalRatingsString: "2.2K+ ratings",
        veg: false,
        sla: { deliveryTime: 19, lastMileTravel: 1.3, slaString: "19 mins" },
        aggregatedDiscountInfoV3: { header: "15% OFF", subHeader: "UPTO ₹40" },
        }
    },
    {
        info: {
        id: "990011",
        name: "Steak Station",
        cloudinaryImageId: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=1200&q=80&auto=format&fit=crop",
        locality: "Indiranagar",
        areaName: "Central District",
        costForTwo: "₹700 for two",
        cuisines: ["Steakhouse", "Grill"],
        avgRating: 4.7,
        avgRatingString: "4.7",
        totalRatingsString: "11K+ ratings",
        veg: false,
        sla: { deliveryTime: 40, lastMileTravel: 5.0, slaString: "40 mins" },
        aggregatedDiscountInfoV3: { header: "60% OFF", subHeader: "UPTO ₹200" },
        }
    },
    {
        info: {
        id: "100122",
        name: "Seafood Shack",
        cloudinaryImageId: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80&auto=format&fit=crop",
        locality: "Marathahalli",
        areaName: "East Zone",
        costForTwo: "₹550 for two",
        cuisines: ["Seafood", "Asian"],
        avgRating: 4.2,
        avgRatingString: "4.2",
        totalRatingsString: "4.5K+ ratings",
        veg: false,
        sla: { deliveryTime: 32, lastMileTravel: 3.6, slaString: "32 mins" },
        aggregatedDiscountInfoV3: { header: "35% OFF", subHeader: "UPTO ₹110" },
        }
    },
    {
        info: {
        id: "101233",
        name: "Vegan Vibes",
        cloudinaryImageId: "https://images.unsplash.com/photo-1528715471579-d6a6f3b1f6f9?w=1200&q=80&auto=format&fit=crop",
        locality: "Koramangala",
        areaName: "Central District",
        costForTwo: "₹330 for two",
        cuisines: ["Vegan", "Healthy"],
        avgRating: 4.5,
        avgRatingString: "4.5",
        totalRatingsString: "6K+ ratings",
        veg: true,
        sla: { deliveryTime: 20, lastMileTravel: 2.1, slaString: "20 mins" },
        aggregatedDiscountInfoV3: { header: "40% OFF", subHeader: "UPTO ₹90" },
        }
    },
];

export default restaurantList;